/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as siteIndexRouteImport } from './routes/(site)/index'
import { Route as UploadsSplatRouteImport } from './routes/uploads.$'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as siteTrocarSenhaRouteImport } from './routes/(site)/trocar-senha'
import { Route as siteResetPasswordRouteImport } from './routes/(site)/reset-password'
import { Route as siteRedefinirSenhaRouteImport } from './routes/(site)/redefinir-senha'
import { Route as siteRecursosRouteImport } from './routes/(site)/recursos'
import { Route as sitePrecosRouteImport } from './routes/(site)/precos'
import { Route as siteLoginRouteImport } from './routes/(site)/login'
import { Route as siteContatoRouteImport } from './routes/(site)/contato'
import { Route as siteCadastroRouteImport } from './routes/(site)/cadastro'
import { Route as publicPerfilPublicoRouteImport } from './routes/(public)/perfil-publico'
import { Route as appWhatsappRouteImport } from './routes/(app)/whatsapp'
import { Route as appUseNoCelularRouteImport } from './routes/(app)/use-no-celular'
import { Route as appTransacoesRouteImport } from './routes/(app)/transacoes'
import { Route as appServicosRouteImport } from './routes/(app)/servicos'
import { Route as appSaudacaoRouteImport } from './routes/(app)/saudacao'
import { Route as appPortfolioRouteImport } from './routes/(app)/portfolio'
import { Route as appPlanoRouteImport } from './routes/(app)/plano'
import { Route as appPersonalizacaoRouteImport } from './routes/(app)/personalizacao'
import { Route as appPerfilProfissionalRouteImport } from './routes/(app)/perfil-profissional'
import { Route as appPagamentosRouteImport } from './routes/(app)/pagamentos'
import { Route as appOnboardingRouteImport } from './routes/(app)/onboarding'
import { Route as appNotificacoesTodasRouteImport } from './routes/(app)/notificacoes-todas'
import { Route as appNotificacoesRouteImport } from './routes/(app)/notificacoes'
import { Route as appMaisRouteImport } from './routes/(app)/mais'
import { Route as appHorariosRouteImport } from './routes/(app)/horarios'
import { Route as appGoogleCalendarRouteImport } from './routes/(app)/google-calendar'
import { Route as appDashboardRouteImport } from './routes/(app)/dashboard'
import { Route as appClientesRouteImport } from './routes/(app)/clientes'
import { Route as appAvaliacoesRouteImport } from './routes/(app)/avaliacoes'
import { Route as appAppRouteImport } from './routes/(app)/app'
import { Route as ApiPublicMpWebhookRouteImport } from './routes/api/public/mp-webhook'
import { Route as ApiFaqSearchRouteImport } from './routes/api/faq/search'
import { Route as publicAvaliarTokenRouteImport } from './routes/(public)/avaliar.$token'
import { Route as publicAgendarSlugRouteImport } from './routes/(public)/agendar.$slug'
import { Route as appServicoNovoRouteImport } from './routes/(app)/servico.novo'
import { Route as appServicoIdRouteImport } from './routes/(app)/servico.$id'
import { Route as adminSuperLoginRouteImport } from './routes/(admin)/super/login'
import { Route as adminSuperAppRouteRouteImport } from './routes/(admin)/super/_app/route'
import { Route as adminSuperAppIndexRouteImport } from './routes/(admin)/super/_app/index'
import { Route as ApiPublicMercadoPagoCallbackRouteImport } from './routes/api/public/mercado-pago.callback'
import { Route as ApiPublicGoogleCalendarCallbackRouteImport } from './routes/api/public/google-calendar.callback'
import { Route as adminSuperAppUsuariosRouteImport } from './routes/(admin)/super/_app/usuarios'
import { Route as adminSuperAppTicketsRouteImport } from './routes/(admin)/super/_app/tickets'
import { Route as adminSuperAppTemplatesRouteImport } from './routes/(admin)/super/_app/templates'
import { Route as adminSuperAppSistemaRouteImport } from './routes/(admin)/super/_app/sistema'
import { Route as adminSuperAppPlanosRouteImport } from './routes/(admin)/super/_app/planos'
import { Route as adminSuperAppNotificacoesRouteImport } from './routes/(admin)/super/_app/notificacoes'
import { Route as adminSuperAppMfaSetupRouteImport } from './routes/(admin)/super/_app/mfa-setup'
import { Route as adminSuperAppMeuPerfilRouteImport } from './routes/(admin)/super/_app/meu-perfil'
import { Route as adminSuperAppInfraRouteImport } from './routes/(admin)/super/_app/infra'
import { Route as adminSuperAppIndicacoesRouteImport } from './routes/(admin)/super/_app/indicacoes'
import { Route as adminSuperAppFinanceiroRouteImport } from './routes/(admin)/super/_app/financeiro'
import { Route as adminSuperAppFaqRouteImport } from './routes/(admin)/super/_app/faq'
import { Route as adminSuperAppConfiguracoesRouteImport } from './routes/(admin)/super/_app/configuracoes'
import { Route as adminSuperAppCobrancasRouteImport } from './routes/(admin)/super/_app/cobrancas'
import { Route as adminSuperAppAuditoriaRouteImport } from './routes/(admin)/super/_app/auditoria'

const siteIndexRoute = siteIndexRouteImport.update({
  id: '/(site)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsSplatRoute = UploadsSplatRouteImport.update({
  id: '/uploads/$',
  path: '/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const siteTrocarSenhaRoute = siteTrocarSenhaRouteImport.update({
  id: '/(site)/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const siteResetPasswordRoute = siteResetPasswordRouteImport.update({
  id: '/(site)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const siteRedefinirSenhaRoute = siteRedefinirSenhaRouteImport.update({
  id: '/(site)/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const siteRecursosRoute = siteRecursosRouteImport.update({
  id: '/(site)/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const sitePrecosRoute = sitePrecosRouteImport.update({
  id: '/(site)/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const siteLoginRoute = siteLoginRouteImport.update({
  id: '/(site)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const siteContatoRoute = siteContatoRouteImport.update({
  id: '/(site)/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const siteCadastroRoute = siteCadastroRouteImport.update({
  id: '/(site)/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPerfilPublicoRoute = publicPerfilPublicoRouteImport.update({
  id: '/(public)/perfil-publico',
  path: '/perfil-publico',
  getParentRoute: () => rootRouteImport,
} as any)
const appWhatsappRoute = appWhatsappRouteImport.update({
  id: '/(app)/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const appUseNoCelularRoute = appUseNoCelularRouteImport.update({
  id: '/(app)/use-no-celular',
  path: '/use-no-celular',
  getParentRoute: () => rootRouteImport,
} as any)
const appTransacoesRoute = appTransacoesRouteImport.update({
  id: '/(app)/transacoes',
  path: '/transacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const appServicosRoute = appServicosRouteImport.update({
  id: '/(app)/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const appSaudacaoRoute = appSaudacaoRouteImport.update({
  id: '/(app)/saudacao',
  path: '/saudacao',
  getParentRoute: () => rootRouteImport,
} as any)
const appPortfolioRoute = appPortfolioRouteImport.update({
  id: '/(app)/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const appPlanoRoute = appPlanoRouteImport.update({
  id: '/(app)/plano',
  path: '/plano',
  getParentRoute: () => rootRouteImport,
} as any)
const appPersonalizacaoRoute = appPersonalizacaoRouteImport.update({
  id: '/(app)/personalizacao',
  path: '/personalizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const appPerfilProfissionalRoute = appPerfilProfissionalRouteImport.update({
  id: '/(app)/perfil-profissional',
  path: '/perfil-profissional',
  getParentRoute: () => rootRouteImport,
} as any)
const appPagamentosRoute = appPagamentosRouteImport.update({
  id: '/(app)/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const appOnboardingRoute = appOnboardingRouteImport.update({
  id: '/(app)/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const appNotificacoesTodasRoute = appNotificacoesTodasRouteImport.update({
  id: '/(app)/notificacoes-todas',
  path: '/notificacoes-todas',
  getParentRoute: () => rootRouteImport,
} as any)
const appNotificacoesRoute = appNotificacoesRouteImport.update({
  id: '/(app)/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const appMaisRoute = appMaisRouteImport.update({
  id: '/(app)/mais',
  path: '/mais',
  getParentRoute: () => rootRouteImport,
} as any)
const appHorariosRoute = appHorariosRouteImport.update({
  id: '/(app)/horarios',
  path: '/horarios',
  getParentRoute: () => rootRouteImport,
} as any)
const appGoogleCalendarRoute = appGoogleCalendarRouteImport.update({
  id: '/(app)/google-calendar',
  path: '/google-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/(app)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const appClientesRoute = appClientesRouteImport.update({
  id: '/(app)/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const appAvaliacoesRoute = appAvaliacoesRouteImport.update({
  id: '/(app)/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppRoute = appAppRouteImport.update({
  id: '/(app)/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpWebhookRoute = ApiPublicMpWebhookRouteImport.update({
  id: '/api/public/mp-webhook',
  path: '/api/public/mp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFaqSearchRoute = ApiFaqSearchRouteImport.update({
  id: '/api/faq/search',
  path: '/api/faq/search',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAvaliarTokenRoute = publicAvaliarTokenRouteImport.update({
  id: '/(public)/avaliar/$token',
  path: '/avaliar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAgendarSlugRoute = publicAgendarSlugRouteImport.update({
  id: '/(public)/agendar/$slug',
  path: '/agendar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const appServicoNovoRoute = appServicoNovoRouteImport.update({
  id: '/(app)/servico/novo',
  path: '/servico/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const appServicoIdRoute = appServicoIdRouteImport.update({
  id: '/(app)/servico/$id',
  path: '/servico/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const adminSuperLoginRoute = adminSuperLoginRouteImport.update({
  id: '/(admin)/super/login',
  path: '/super/login',
  getParentRoute: () => rootRouteImport,
} as any)
const adminSuperAppRouteRoute = adminSuperAppRouteRouteImport.update({
  id: '/(admin)/super/_app',
  path: '/super',
  getParentRoute: () => rootRouteImport,
} as any)
const adminSuperAppIndexRoute = adminSuperAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => adminSuperAppRouteRoute,
} as any)
const ApiPublicMercadoPagoCallbackRoute =
  ApiPublicMercadoPagoCallbackRouteImport.update({
    id: '/api/public/mercado-pago/callback',
    path: '/api/public/mercado-pago/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleCalendarCallbackRoute =
  ApiPublicGoogleCalendarCallbackRouteImport.update({
    id: '/api/public/google-calendar/callback',
    path: '/api/public/google-calendar/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const adminSuperAppUsuariosRoute = adminSuperAppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => adminSuperAppRouteRoute,
} as any)
const adminSuperAppTicketsRoute = adminSuperAppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => adminSuperAppRouteRoute,
} as any)
const adminSuperAppTemplatesRoute = adminSuperAppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => adminSuperAppRouteRoute,
} as any)
const adminSuperAppSistemaRoute = adminSuperAppSistemaRouteImport.update({
  id: '/sistema',
  path: '/sistema',
  getParentRoute: () => adminSuperAppRouteRoute,
} as any)
const adminSuperAppPlanosRoute = adminSuperAppPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => adminSuperAppRouteRoute,
} as any)
const adminSuperAppNotificacoesRoute =
  adminSuperAppNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => adminSuperAppRouteRoute,
  } as any)
const adminSuperAppMfaSetupRoute = adminSuperAppMfaSetupRouteImport.update({
  id: '/mfa-setup',
  path: '/mfa-setup',
  getParentRoute: () => adminSuperAppRouteRoute,
} as any)
const adminSuperAppMeuPerfilRoute = adminSuperAppMeuPerfilRouteImport.update({
  id: '/meu-perfil',
  path: '/meu-perfil',
  getParentRoute: () => adminSuperAppRouteRoute,
} as any)
const adminSuperAppInfraRoute = adminSuperAppInfraRouteImport.update({
  id: '/infra',
  path: '/infra',
  getParentRoute: () => adminSuperAppRouteRoute,
} as any)
const adminSuperAppIndicacoesRoute = adminSuperAppIndicacoesRouteImport.update({
  id: '/indicacoes',
  path: '/indicacoes',
  getParentRoute: () => adminSuperAppRouteRoute,
} as any)
const adminSuperAppFinanceiroRoute = adminSuperAppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => adminSuperAppRouteRoute,
} as any)
const adminSuperAppFaqRoute = adminSuperAppFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => adminSuperAppRouteRoute,
} as any)
const adminSuperAppConfiguracoesRoute =
  adminSuperAppConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => adminSuperAppRouteRoute,
  } as any)
const adminSuperAppCobrancasRoute = adminSuperAppCobrancasRouteImport.update({
  id: '/cobrancas',
  path: '/cobrancas',
  getParentRoute: () => adminSuperAppRouteRoute,
} as any)
const adminSuperAppAuditoriaRoute = adminSuperAppAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => adminSuperAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof appAppRoute
  '/avaliacoes': typeof appAvaliacoesRoute
  '/clientes': typeof appClientesRoute
  '/dashboard': typeof appDashboardRoute
  '/google-calendar': typeof appGoogleCalendarRoute
  '/horarios': typeof appHorariosRoute
  '/mais': typeof appMaisRoute
  '/notificacoes': typeof appNotificacoesRoute
  '/notificacoes-todas': typeof appNotificacoesTodasRoute
  '/onboarding': typeof appOnboardingRoute
  '/pagamentos': typeof appPagamentosRoute
  '/perfil-profissional': typeof appPerfilProfissionalRoute
  '/personalizacao': typeof appPersonalizacaoRoute
  '/plano': typeof appPlanoRoute
  '/portfolio': typeof appPortfolioRoute
  '/saudacao': typeof appSaudacaoRoute
  '/servicos': typeof appServicosRoute
  '/transacoes': typeof appTransacoesRoute
  '/use-no-celular': typeof appUseNoCelularRoute
  '/whatsapp': typeof appWhatsappRoute
  '/perfil-publico': typeof publicPerfilPublicoRoute
  '/cadastro': typeof siteCadastroRoute
  '/contato': typeof siteContatoRoute
  '/login': typeof siteLoginRoute
  '/precos': typeof sitePrecosRoute
  '/recursos': typeof siteRecursosRoute
  '/redefinir-senha': typeof siteRedefinirSenhaRoute
  '/reset-password': typeof siteResetPasswordRoute
  '/trocar-senha': typeof siteTrocarSenhaRoute
  '/api/health': typeof ApiHealthRoute
  '/api/upload': typeof ApiUploadRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/': typeof siteIndexRoute
  '/super': typeof adminSuperAppRouteRouteWithChildren
  '/super/login': typeof adminSuperLoginRoute
  '/servico/$id': typeof appServicoIdRoute
  '/servico/novo': typeof appServicoNovoRoute
  '/agendar/$slug': typeof publicAgendarSlugRoute
  '/avaliar/$token': typeof publicAvaliarTokenRoute
  '/api/faq/search': typeof ApiFaqSearchRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/super/auditoria': typeof adminSuperAppAuditoriaRoute
  '/super/cobrancas': typeof adminSuperAppCobrancasRoute
  '/super/configuracoes': typeof adminSuperAppConfiguracoesRoute
  '/super/faq': typeof adminSuperAppFaqRoute
  '/super/financeiro': typeof adminSuperAppFinanceiroRoute
  '/super/indicacoes': typeof adminSuperAppIndicacoesRoute
  '/super/infra': typeof adminSuperAppInfraRoute
  '/super/meu-perfil': typeof adminSuperAppMeuPerfilRoute
  '/super/mfa-setup': typeof adminSuperAppMfaSetupRoute
  '/super/notificacoes': typeof adminSuperAppNotificacoesRoute
  '/super/planos': typeof adminSuperAppPlanosRoute
  '/super/sistema': typeof adminSuperAppSistemaRoute
  '/super/templates': typeof adminSuperAppTemplatesRoute
  '/super/tickets': typeof adminSuperAppTicketsRoute
  '/super/usuarios': typeof adminSuperAppUsuariosRoute
  '/api/public/google-calendar/callback': typeof ApiPublicGoogleCalendarCallbackRoute
  '/api/public/mercado-pago/callback': typeof ApiPublicMercadoPagoCallbackRoute
  '/super/': typeof adminSuperAppIndexRoute
}
export interface FileRoutesByTo {
  '/app': typeof appAppRoute
  '/avaliacoes': typeof appAvaliacoesRoute
  '/clientes': typeof appClientesRoute
  '/dashboard': typeof appDashboardRoute
  '/google-calendar': typeof appGoogleCalendarRoute
  '/horarios': typeof appHorariosRoute
  '/mais': typeof appMaisRoute
  '/notificacoes': typeof appNotificacoesRoute
  '/notificacoes-todas': typeof appNotificacoesTodasRoute
  '/onboarding': typeof appOnboardingRoute
  '/pagamentos': typeof appPagamentosRoute
  '/perfil-profissional': typeof appPerfilProfissionalRoute
  '/personalizacao': typeof appPersonalizacaoRoute
  '/plano': typeof appPlanoRoute
  '/portfolio': typeof appPortfolioRoute
  '/saudacao': typeof appSaudacaoRoute
  '/servicos': typeof appServicosRoute
  '/transacoes': typeof appTransacoesRoute
  '/use-no-celular': typeof appUseNoCelularRoute
  '/whatsapp': typeof appWhatsappRoute
  '/perfil-publico': typeof publicPerfilPublicoRoute
  '/cadastro': typeof siteCadastroRoute
  '/contato': typeof siteContatoRoute
  '/login': typeof siteLoginRoute
  '/precos': typeof sitePrecosRoute
  '/recursos': typeof siteRecursosRoute
  '/redefinir-senha': typeof siteRedefinirSenhaRoute
  '/reset-password': typeof siteResetPasswordRoute
  '/trocar-senha': typeof siteTrocarSenhaRoute
  '/api/health': typeof ApiHealthRoute
  '/api/upload': typeof ApiUploadRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/': typeof siteIndexRoute
  '/super/login': typeof adminSuperLoginRoute
  '/servico/$id': typeof appServicoIdRoute
  '/servico/novo': typeof appServicoNovoRoute
  '/agendar/$slug': typeof publicAgendarSlugRoute
  '/avaliar/$token': typeof publicAvaliarTokenRoute
  '/api/faq/search': typeof ApiFaqSearchRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/super/auditoria': typeof adminSuperAppAuditoriaRoute
  '/super/cobrancas': typeof adminSuperAppCobrancasRoute
  '/super/configuracoes': typeof adminSuperAppConfiguracoesRoute
  '/super/faq': typeof adminSuperAppFaqRoute
  '/super/financeiro': typeof adminSuperAppFinanceiroRoute
  '/super/indicacoes': typeof adminSuperAppIndicacoesRoute
  '/super/infra': typeof adminSuperAppInfraRoute
  '/super/meu-perfil': typeof adminSuperAppMeuPerfilRoute
  '/super/mfa-setup': typeof adminSuperAppMfaSetupRoute
  '/super/notificacoes': typeof adminSuperAppNotificacoesRoute
  '/super/planos': typeof adminSuperAppPlanosRoute
  '/super/sistema': typeof adminSuperAppSistemaRoute
  '/super/templates': typeof adminSuperAppTemplatesRoute
  '/super/tickets': typeof adminSuperAppTicketsRoute
  '/super/usuarios': typeof adminSuperAppUsuariosRoute
  '/api/public/google-calendar/callback': typeof ApiPublicGoogleCalendarCallbackRoute
  '/api/public/mercado-pago/callback': typeof ApiPublicMercadoPagoCallbackRoute
  '/super': typeof adminSuperAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/app': typeof appAppRoute
  '/(app)/avaliacoes': typeof appAvaliacoesRoute
  '/(app)/clientes': typeof appClientesRoute
  '/(app)/dashboard': typeof appDashboardRoute
  '/(app)/google-calendar': typeof appGoogleCalendarRoute
  '/(app)/horarios': typeof appHorariosRoute
  '/(app)/mais': typeof appMaisRoute
  '/(app)/notificacoes': typeof appNotificacoesRoute
  '/(app)/notificacoes-todas': typeof appNotificacoesTodasRoute
  '/(app)/onboarding': typeof appOnboardingRoute
  '/(app)/pagamentos': typeof appPagamentosRoute
  '/(app)/perfil-profissional': typeof appPerfilProfissionalRoute
  '/(app)/personalizacao': typeof appPersonalizacaoRoute
  '/(app)/plano': typeof appPlanoRoute
  '/(app)/portfolio': typeof appPortfolioRoute
  '/(app)/saudacao': typeof appSaudacaoRoute
  '/(app)/servicos': typeof appServicosRoute
  '/(app)/transacoes': typeof appTransacoesRoute
  '/(app)/use-no-celular': typeof appUseNoCelularRoute
  '/(app)/whatsapp': typeof appWhatsappRoute
  '/(public)/perfil-publico': typeof publicPerfilPublicoRoute
  '/(site)/cadastro': typeof siteCadastroRoute
  '/(site)/contato': typeof siteContatoRoute
  '/(site)/login': typeof siteLoginRoute
  '/(site)/precos': typeof sitePrecosRoute
  '/(site)/recursos': typeof siteRecursosRoute
  '/(site)/redefinir-senha': typeof siteRedefinirSenhaRoute
  '/(site)/reset-password': typeof siteResetPasswordRoute
  '/(site)/trocar-senha': typeof siteTrocarSenhaRoute
  '/api/health': typeof ApiHealthRoute
  '/api/upload': typeof ApiUploadRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/(site)/': typeof siteIndexRoute
  '/(admin)/super/_app': typeof adminSuperAppRouteRouteWithChildren
  '/(admin)/super/login': typeof adminSuperLoginRoute
  '/(app)/servico/$id': typeof appServicoIdRoute
  '/(app)/servico/novo': typeof appServicoNovoRoute
  '/(public)/agendar/$slug': typeof publicAgendarSlugRoute
  '/(public)/avaliar/$token': typeof publicAvaliarTokenRoute
  '/api/faq/search': typeof ApiFaqSearchRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/(admin)/super/_app/auditoria': typeof adminSuperAppAuditoriaRoute
  '/(admin)/super/_app/cobrancas': typeof adminSuperAppCobrancasRoute
  '/(admin)/super/_app/configuracoes': typeof adminSuperAppConfiguracoesRoute
  '/(admin)/super/_app/faq': typeof adminSuperAppFaqRoute
  '/(admin)/super/_app/financeiro': typeof adminSuperAppFinanceiroRoute
  '/(admin)/super/_app/indicacoes': typeof adminSuperAppIndicacoesRoute
  '/(admin)/super/_app/infra': typeof adminSuperAppInfraRoute
  '/(admin)/super/_app/meu-perfil': typeof adminSuperAppMeuPerfilRoute
  '/(admin)/super/_app/mfa-setup': typeof adminSuperAppMfaSetupRoute
  '/(admin)/super/_app/notificacoes': typeof adminSuperAppNotificacoesRoute
  '/(admin)/super/_app/planos': typeof adminSuperAppPlanosRoute
  '/(admin)/super/_app/sistema': typeof adminSuperAppSistemaRoute
  '/(admin)/super/_app/templates': typeof adminSuperAppTemplatesRoute
  '/(admin)/super/_app/tickets': typeof adminSuperAppTicketsRoute
  '/(admin)/super/_app/usuarios': typeof adminSuperAppUsuariosRoute
  '/api/public/google-calendar/callback': typeof ApiPublicGoogleCalendarCallbackRoute
  '/api/public/mercado-pago/callback': typeof ApiPublicMercadoPagoCallbackRoute
  '/(admin)/super/_app/': typeof adminSuperAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/avaliacoes'
    | '/clientes'
    | '/dashboard'
    | '/google-calendar'
    | '/horarios'
    | '/mais'
    | '/notificacoes'
    | '/notificacoes-todas'
    | '/onboarding'
    | '/pagamentos'
    | '/perfil-profissional'
    | '/personalizacao'
    | '/plano'
    | '/portfolio'
    | '/saudacao'
    | '/servicos'
    | '/transacoes'
    | '/use-no-celular'
    | '/whatsapp'
    | '/perfil-publico'
    | '/cadastro'
    | '/contato'
    | '/login'
    | '/precos'
    | '/recursos'
    | '/redefinir-senha'
    | '/reset-password'
    | '/trocar-senha'
    | '/api/health'
    | '/api/upload'
    | '/uploads/$'
    | '/'
    | '/super'
    | '/super/login'
    | '/servico/$id'
    | '/servico/novo'
    | '/agendar/$slug'
    | '/avaliar/$token'
    | '/api/faq/search'
    | '/api/public/mp-webhook'
    | '/super/auditoria'
    | '/super/cobrancas'
    | '/super/configuracoes'
    | '/super/faq'
    | '/super/financeiro'
    | '/super/indicacoes'
    | '/super/infra'
    | '/super/meu-perfil'
    | '/super/mfa-setup'
    | '/super/notificacoes'
    | '/super/planos'
    | '/super/sistema'
    | '/super/templates'
    | '/super/tickets'
    | '/super/usuarios'
    | '/api/public/google-calendar/callback'
    | '/api/public/mercado-pago/callback'
    | '/super/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/avaliacoes'
    | '/clientes'
    | '/dashboard'
    | '/google-calendar'
    | '/horarios'
    | '/mais'
    | '/notificacoes'
    | '/notificacoes-todas'
    | '/onboarding'
    | '/pagamentos'
    | '/perfil-profissional'
    | '/personalizacao'
    | '/plano'
    | '/portfolio'
    | '/saudacao'
    | '/servicos'
    | '/transacoes'
    | '/use-no-celular'
    | '/whatsapp'
    | '/perfil-publico'
    | '/cadastro'
    | '/contato'
    | '/login'
    | '/precos'
    | '/recursos'
    | '/redefinir-senha'
    | '/reset-password'
    | '/trocar-senha'
    | '/api/health'
    | '/api/upload'
    | '/uploads/$'
    | '/'
    | '/super/login'
    | '/servico/$id'
    | '/servico/novo'
    | '/agendar/$slug'
    | '/avaliar/$token'
    | '/api/faq/search'
    | '/api/public/mp-webhook'
    | '/super/auditoria'
    | '/super/cobrancas'
    | '/super/configuracoes'
    | '/super/faq'
    | '/super/financeiro'
    | '/super/indicacoes'
    | '/super/infra'
    | '/super/meu-perfil'
    | '/super/mfa-setup'
    | '/super/notificacoes'
    | '/super/planos'
    | '/super/sistema'
    | '/super/templates'
    | '/super/tickets'
    | '/super/usuarios'
    | '/api/public/google-calendar/callback'
    | '/api/public/mercado-pago/callback'
    | '/super'
  id:
    | '__root__'
    | '/(app)/app'
    | '/(app)/avaliacoes'
    | '/(app)/clientes'
    | '/(app)/dashboard'
    | '/(app)/google-calendar'
    | '/(app)/horarios'
    | '/(app)/mais'
    | '/(app)/notificacoes'
    | '/(app)/notificacoes-todas'
    | '/(app)/onboarding'
    | '/(app)/pagamentos'
    | '/(app)/perfil-profissional'
    | '/(app)/personalizacao'
    | '/(app)/plano'
    | '/(app)/portfolio'
    | '/(app)/saudacao'
    | '/(app)/servicos'
    | '/(app)/transacoes'
    | '/(app)/use-no-celular'
    | '/(app)/whatsapp'
    | '/(public)/perfil-publico'
    | '/(site)/cadastro'
    | '/(site)/contato'
    | '/(site)/login'
    | '/(site)/precos'
    | '/(site)/recursos'
    | '/(site)/redefinir-senha'
    | '/(site)/reset-password'
    | '/(site)/trocar-senha'
    | '/api/health'
    | '/api/upload'
    | '/uploads/$'
    | '/(site)/'
    | '/(admin)/super/_app'
    | '/(admin)/super/login'
    | '/(app)/servico/$id'
    | '/(app)/servico/novo'
    | '/(public)/agendar/$slug'
    | '/(public)/avaliar/$token'
    | '/api/faq/search'
    | '/api/public/mp-webhook'
    | '/(admin)/super/_app/auditoria'
    | '/(admin)/super/_app/cobrancas'
    | '/(admin)/super/_app/configuracoes'
    | '/(admin)/super/_app/faq'
    | '/(admin)/super/_app/financeiro'
    | '/(admin)/super/_app/indicacoes'
    | '/(admin)/super/_app/infra'
    | '/(admin)/super/_app/meu-perfil'
    | '/(admin)/super/_app/mfa-setup'
    | '/(admin)/super/_app/notificacoes'
    | '/(admin)/super/_app/planos'
    | '/(admin)/super/_app/sistema'
    | '/(admin)/super/_app/templates'
    | '/(admin)/super/_app/tickets'
    | '/(admin)/super/_app/usuarios'
    | '/api/public/google-calendar/callback'
    | '/api/public/mercado-pago/callback'
    | '/(admin)/super/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appAppRoute: typeof appAppRoute
  appAvaliacoesRoute: typeof appAvaliacoesRoute
  appClientesRoute: typeof appClientesRoute
  appDashboardRoute: typeof appDashboardRoute
  appGoogleCalendarRoute: typeof appGoogleCalendarRoute
  appHorariosRoute: typeof appHorariosRoute
  appMaisRoute: typeof appMaisRoute
  appNotificacoesRoute: typeof appNotificacoesRoute
  appNotificacoesTodasRoute: typeof appNotificacoesTodasRoute
  appOnboardingRoute: typeof appOnboardingRoute
  appPagamentosRoute: typeof appPagamentosRoute
  appPerfilProfissionalRoute: typeof appPerfilProfissionalRoute
  appPersonalizacaoRoute: typeof appPersonalizacaoRoute
  appPlanoRoute: typeof appPlanoRoute
  appPortfolioRoute: typeof appPortfolioRoute
  appSaudacaoRoute: typeof appSaudacaoRoute
  appServicosRoute: typeof appServicosRoute
  appTransacoesRoute: typeof appTransacoesRoute
  appUseNoCelularRoute: typeof appUseNoCelularRoute
  appWhatsappRoute: typeof appWhatsappRoute
  publicPerfilPublicoRoute: typeof publicPerfilPublicoRoute
  siteCadastroRoute: typeof siteCadastroRoute
  siteContatoRoute: typeof siteContatoRoute
  siteLoginRoute: typeof siteLoginRoute
  sitePrecosRoute: typeof sitePrecosRoute
  siteRecursosRoute: typeof siteRecursosRoute
  siteRedefinirSenhaRoute: typeof siteRedefinirSenhaRoute
  siteResetPasswordRoute: typeof siteResetPasswordRoute
  siteTrocarSenhaRoute: typeof siteTrocarSenhaRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiUploadRoute: typeof ApiUploadRoute
  UploadsSplatRoute: typeof UploadsSplatRoute
  siteIndexRoute: typeof siteIndexRoute
  adminSuperAppRouteRoute: typeof adminSuperAppRouteRouteWithChildren
  adminSuperLoginRoute: typeof adminSuperLoginRoute
  appServicoIdRoute: typeof appServicoIdRoute
  appServicoNovoRoute: typeof appServicoNovoRoute
  publicAgendarSlugRoute: typeof publicAgendarSlugRoute
  publicAvaliarTokenRoute: typeof publicAvaliarTokenRoute
  ApiFaqSearchRoute: typeof ApiFaqSearchRoute
  ApiPublicMpWebhookRoute: typeof ApiPublicMpWebhookRoute
  ApiPublicGoogleCalendarCallbackRoute: typeof ApiPublicGoogleCalendarCallbackRoute
  ApiPublicMercadoPagoCallbackRoute: typeof ApiPublicMercadoPagoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(site)/': {
      id: '/(site)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof siteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads/$': {
      id: '/uploads/$'
      path: '/uploads/$'
      fullPath: '/uploads/$'
      preLoaderRoute: typeof UploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(site)/trocar-senha': {
      id: '/(site)/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof siteTrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(site)/reset-password': {
      id: '/(site)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof siteResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(site)/redefinir-senha': {
      id: '/(site)/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof siteRedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(site)/recursos': {
      id: '/(site)/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof siteRecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(site)/precos': {
      id: '/(site)/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof sitePrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(site)/login': {
      id: '/(site)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof siteLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(site)/contato': {
      id: '/(site)/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof siteContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(site)/cadastro': {
      id: '/(site)/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof siteCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/perfil-publico': {
      id: '/(public)/perfil-publico'
      path: '/perfil-publico'
      fullPath: '/perfil-publico'
      preLoaderRoute: typeof publicPerfilPublicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/whatsapp': {
      id: '/(app)/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof appWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/use-no-celular': {
      id: '/(app)/use-no-celular'
      path: '/use-no-celular'
      fullPath: '/use-no-celular'
      preLoaderRoute: typeof appUseNoCelularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/transacoes': {
      id: '/(app)/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof appTransacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/servicos': {
      id: '/(app)/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof appServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/saudacao': {
      id: '/(app)/saudacao'
      path: '/saudacao'
      fullPath: '/saudacao'
      preLoaderRoute: typeof appSaudacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/portfolio': {
      id: '/(app)/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof appPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/plano': {
      id: '/(app)/plano'
      path: '/plano'
      fullPath: '/plano'
      preLoaderRoute: typeof appPlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/personalizacao': {
      id: '/(app)/personalizacao'
      path: '/personalizacao'
      fullPath: '/personalizacao'
      preLoaderRoute: typeof appPersonalizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/perfil-profissional': {
      id: '/(app)/perfil-profissional'
      path: '/perfil-profissional'
      fullPath: '/perfil-profissional'
      preLoaderRoute: typeof appPerfilProfissionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/pagamentos': {
      id: '/(app)/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof appPagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/onboarding': {
      id: '/(app)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof appOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/notificacoes-todas': {
      id: '/(app)/notificacoes-todas'
      path: '/notificacoes-todas'
      fullPath: '/notificacoes-todas'
      preLoaderRoute: typeof appNotificacoesTodasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/notificacoes': {
      id: '/(app)/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof appNotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/mais': {
      id: '/(app)/mais'
      path: '/mais'
      fullPath: '/mais'
      preLoaderRoute: typeof appMaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/horarios': {
      id: '/(app)/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof appHorariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/google-calendar': {
      id: '/(app)/google-calendar'
      path: '/google-calendar'
      fullPath: '/google-calendar'
      preLoaderRoute: typeof appGoogleCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/clientes': {
      id: '/(app)/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof appClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/avaliacoes': {
      id: '/(app)/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof appAvaliacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/app': {
      id: '/(app)/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof appAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mp-webhook': {
      id: '/api/public/mp-webhook'
      path: '/api/public/mp-webhook'
      fullPath: '/api/public/mp-webhook'
      preLoaderRoute: typeof ApiPublicMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/faq/search': {
      id: '/api/faq/search'
      path: '/api/faq/search'
      fullPath: '/api/faq/search'
      preLoaderRoute: typeof ApiFaqSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/avaliar/$token': {
      id: '/(public)/avaliar/$token'
      path: '/avaliar/$token'
      fullPath: '/avaliar/$token'
      preLoaderRoute: typeof publicAvaliarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/agendar/$slug': {
      id: '/(public)/agendar/$slug'
      path: '/agendar/$slug'
      fullPath: '/agendar/$slug'
      preLoaderRoute: typeof publicAgendarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/servico/novo': {
      id: '/(app)/servico/novo'
      path: '/servico/novo'
      fullPath: '/servico/novo'
      preLoaderRoute: typeof appServicoNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/servico/$id': {
      id: '/(app)/servico/$id'
      path: '/servico/$id'
      fullPath: '/servico/$id'
      preLoaderRoute: typeof appServicoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/super/login': {
      id: '/(admin)/super/login'
      path: '/super/login'
      fullPath: '/super/login'
      preLoaderRoute: typeof adminSuperLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/super/_app': {
      id: '/(admin)/super/_app'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof adminSuperAppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/super/_app/': {
      id: '/(admin)/super/_app/'
      path: '/'
      fullPath: '/super/'
      preLoaderRoute: typeof adminSuperAppIndexRouteImport
      parentRoute: typeof adminSuperAppRouteRoute
    }
    '/api/public/mercado-pago/callback': {
      id: '/api/public/mercado-pago/callback'
      path: '/api/public/mercado-pago/callback'
      fullPath: '/api/public/mercado-pago/callback'
      preLoaderRoute: typeof ApiPublicMercadoPagoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-calendar/callback': {
      id: '/api/public/google-calendar/callback'
      path: '/api/public/google-calendar/callback'
      fullPath: '/api/public/google-calendar/callback'
      preLoaderRoute: typeof ApiPublicGoogleCalendarCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/super/_app/usuarios': {
      id: '/(admin)/super/_app/usuarios'
      path: '/usuarios'
      fullPath: '/super/usuarios'
      preLoaderRoute: typeof adminSuperAppUsuariosRouteImport
      parentRoute: typeof adminSuperAppRouteRoute
    }
    '/(admin)/super/_app/tickets': {
      id: '/(admin)/super/_app/tickets'
      path: '/tickets'
      fullPath: '/super/tickets'
      preLoaderRoute: typeof adminSuperAppTicketsRouteImport
      parentRoute: typeof adminSuperAppRouteRoute
    }
    '/(admin)/super/_app/templates': {
      id: '/(admin)/super/_app/templates'
      path: '/templates'
      fullPath: '/super/templates'
      preLoaderRoute: typeof adminSuperAppTemplatesRouteImport
      parentRoute: typeof adminSuperAppRouteRoute
    }
    '/(admin)/super/_app/sistema': {
      id: '/(admin)/super/_app/sistema'
      path: '/sistema'
      fullPath: '/super/sistema'
      preLoaderRoute: typeof adminSuperAppSistemaRouteImport
      parentRoute: typeof adminSuperAppRouteRoute
    }
    '/(admin)/super/_app/planos': {
      id: '/(admin)/super/_app/planos'
      path: '/planos'
      fullPath: '/super/planos'
      preLoaderRoute: typeof adminSuperAppPlanosRouteImport
      parentRoute: typeof adminSuperAppRouteRoute
    }
    '/(admin)/super/_app/notificacoes': {
      id: '/(admin)/super/_app/notificacoes'
      path: '/notificacoes'
      fullPath: '/super/notificacoes'
      preLoaderRoute: typeof adminSuperAppNotificacoesRouteImport
      parentRoute: typeof adminSuperAppRouteRoute
    }
    '/(admin)/super/_app/mfa-setup': {
      id: '/(admin)/super/_app/mfa-setup'
      path: '/mfa-setup'
      fullPath: '/super/mfa-setup'
      preLoaderRoute: typeof adminSuperAppMfaSetupRouteImport
      parentRoute: typeof adminSuperAppRouteRoute
    }
    '/(admin)/super/_app/meu-perfil': {
      id: '/(admin)/super/_app/meu-perfil'
      path: '/meu-perfil'
      fullPath: '/super/meu-perfil'
      preLoaderRoute: typeof adminSuperAppMeuPerfilRouteImport
      parentRoute: typeof adminSuperAppRouteRoute
    }
    '/(admin)/super/_app/infra': {
      id: '/(admin)/super/_app/infra'
      path: '/infra'
      fullPath: '/super/infra'
      preLoaderRoute: typeof adminSuperAppInfraRouteImport
      parentRoute: typeof adminSuperAppRouteRoute
    }
    '/(admin)/super/_app/indicacoes': {
      id: '/(admin)/super/_app/indicacoes'
      path: '/indicacoes'
      fullPath: '/super/indicacoes'
      preLoaderRoute: typeof adminSuperAppIndicacoesRouteImport
      parentRoute: typeof adminSuperAppRouteRoute
    }
    '/(admin)/super/_app/financeiro': {
      id: '/(admin)/super/_app/financeiro'
      path: '/financeiro'
      fullPath: '/super/financeiro'
      preLoaderRoute: typeof adminSuperAppFinanceiroRouteImport
      parentRoute: typeof adminSuperAppRouteRoute
    }
    '/(admin)/super/_app/faq': {
      id: '/(admin)/super/_app/faq'
      path: '/faq'
      fullPath: '/super/faq'
      preLoaderRoute: typeof adminSuperAppFaqRouteImport
      parentRoute: typeof adminSuperAppRouteRoute
    }
    '/(admin)/super/_app/configuracoes': {
      id: '/(admin)/super/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/super/configuracoes'
      preLoaderRoute: typeof adminSuperAppConfiguracoesRouteImport
      parentRoute: typeof adminSuperAppRouteRoute
    }
    '/(admin)/super/_app/cobrancas': {
      id: '/(admin)/super/_app/cobrancas'
      path: '/cobrancas'
      fullPath: '/super/cobrancas'
      preLoaderRoute: typeof adminSuperAppCobrancasRouteImport
      parentRoute: typeof adminSuperAppRouteRoute
    }
    '/(admin)/super/_app/auditoria': {
      id: '/(admin)/super/_app/auditoria'
      path: '/auditoria'
      fullPath: '/super/auditoria'
      preLoaderRoute: typeof adminSuperAppAuditoriaRouteImport
      parentRoute: typeof adminSuperAppRouteRoute
    }
  }
}

interface adminSuperAppRouteRouteChildren {
  adminSuperAppAuditoriaRoute: typeof adminSuperAppAuditoriaRoute
  adminSuperAppCobrancasRoute: typeof adminSuperAppCobrancasRoute
  adminSuperAppConfiguracoesRoute: typeof adminSuperAppConfiguracoesRoute
  adminSuperAppFaqRoute: typeof adminSuperAppFaqRoute
  adminSuperAppFinanceiroRoute: typeof adminSuperAppFinanceiroRoute
  adminSuperAppIndicacoesRoute: typeof adminSuperAppIndicacoesRoute
  adminSuperAppInfraRoute: typeof adminSuperAppInfraRoute
  adminSuperAppMeuPerfilRoute: typeof adminSuperAppMeuPerfilRoute
  adminSuperAppMfaSetupRoute: typeof adminSuperAppMfaSetupRoute
  adminSuperAppNotificacoesRoute: typeof adminSuperAppNotificacoesRoute
  adminSuperAppPlanosRoute: typeof adminSuperAppPlanosRoute
  adminSuperAppSistemaRoute: typeof adminSuperAppSistemaRoute
  adminSuperAppTemplatesRoute: typeof adminSuperAppTemplatesRoute
  adminSuperAppTicketsRoute: typeof adminSuperAppTicketsRoute
  adminSuperAppUsuariosRoute: typeof adminSuperAppUsuariosRoute
  adminSuperAppIndexRoute: typeof adminSuperAppIndexRoute
}

const adminSuperAppRouteRouteChildren: adminSuperAppRouteRouteChildren = {
  adminSuperAppAuditoriaRoute: adminSuperAppAuditoriaRoute,
  adminSuperAppCobrancasRoute: adminSuperAppCobrancasRoute,
  adminSuperAppConfiguracoesRoute: adminSuperAppConfiguracoesRoute,
  adminSuperAppFaqRoute: adminSuperAppFaqRoute,
  adminSuperAppFinanceiroRoute: adminSuperAppFinanceiroRoute,
  adminSuperAppIndicacoesRoute: adminSuperAppIndicacoesRoute,
  adminSuperAppInfraRoute: adminSuperAppInfraRoute,
  adminSuperAppMeuPerfilRoute: adminSuperAppMeuPerfilRoute,
  adminSuperAppMfaSetupRoute: adminSuperAppMfaSetupRoute,
  adminSuperAppNotificacoesRoute: adminSuperAppNotificacoesRoute,
  adminSuperAppPlanosRoute: adminSuperAppPlanosRoute,
  adminSuperAppSistemaRoute: adminSuperAppSistemaRoute,
  adminSuperAppTemplatesRoute: adminSuperAppTemplatesRoute,
  adminSuperAppTicketsRoute: adminSuperAppTicketsRoute,
  adminSuperAppUsuariosRoute: adminSuperAppUsuariosRoute,
  adminSuperAppIndexRoute: adminSuperAppIndexRoute,
}

const adminSuperAppRouteRouteWithChildren =
  adminSuperAppRouteRoute._addFileChildren(adminSuperAppRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  appAppRoute: appAppRoute,
  appAvaliacoesRoute: appAvaliacoesRoute,
  appClientesRoute: appClientesRoute,
  appDashboardRoute: appDashboardRoute,
  appGoogleCalendarRoute: appGoogleCalendarRoute,
  appHorariosRoute: appHorariosRoute,
  appMaisRoute: appMaisRoute,
  appNotificacoesRoute: appNotificacoesRoute,
  appNotificacoesTodasRoute: appNotificacoesTodasRoute,
  appOnboardingRoute: appOnboardingRoute,
  appPagamentosRoute: appPagamentosRoute,
  appPerfilProfissionalRoute: appPerfilProfissionalRoute,
  appPersonalizacaoRoute: appPersonalizacaoRoute,
  appPlanoRoute: appPlanoRoute,
  appPortfolioRoute: appPortfolioRoute,
  appSaudacaoRoute: appSaudacaoRoute,
  appServicosRoute: appServicosRoute,
  appTransacoesRoute: appTransacoesRoute,
  appUseNoCelularRoute: appUseNoCelularRoute,
  appWhatsappRoute: appWhatsappRoute,
  publicPerfilPublicoRoute: publicPerfilPublicoRoute,
  siteCadastroRoute: siteCadastroRoute,
  siteContatoRoute: siteContatoRoute,
  siteLoginRoute: siteLoginRoute,
  sitePrecosRoute: sitePrecosRoute,
  siteRecursosRoute: siteRecursosRoute,
  siteRedefinirSenhaRoute: siteRedefinirSenhaRoute,
  siteResetPasswordRoute: siteResetPasswordRoute,
  siteTrocarSenhaRoute: siteTrocarSenhaRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiUploadRoute: ApiUploadRoute,
  UploadsSplatRoute: UploadsSplatRoute,
  siteIndexRoute: siteIndexRoute,
  adminSuperAppRouteRoute: adminSuperAppRouteRouteWithChildren,
  adminSuperLoginRoute: adminSuperLoginRoute,
  appServicoIdRoute: appServicoIdRoute,
  appServicoNovoRoute: appServicoNovoRoute,
  publicAgendarSlugRoute: publicAgendarSlugRoute,
  publicAvaliarTokenRoute: publicAvaliarTokenRoute,
  ApiFaqSearchRoute: ApiFaqSearchRoute,
  ApiPublicMpWebhookRoute: ApiPublicMpWebhookRoute,
  ApiPublicGoogleCalendarCallbackRoute: ApiPublicGoogleCalendarCallbackRoute,
  ApiPublicMercadoPagoCallbackRoute: ApiPublicMercadoPagoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
