/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as TransacoesRouteImport } from './routes/transacoes'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as SaudacaoRouteImport } from './routes/saudacao'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PlanoRouteImport } from './routes/plano'
import { Route as PersonalizacaoRouteImport } from './routes/personalizacao'
import { Route as PerfilPublicoRouteImport } from './routes/perfil-publico'
import { Route as PerfilProfissionalRouteImport } from './routes/perfil-profissional'
import { Route as PagamentosRouteImport } from './routes/pagamentos'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificacoesTodasRouteImport } from './routes/notificacoes-todas'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as MaisRouteImport } from './routes/mais'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HorariosRouteImport } from './routes/horarios'
import { Route as GoogleCalendarRouteImport } from './routes/google-calendar'
import { Route as ExemploPaginaRouteImport } from './routes/exemplo-pagina'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AvaliacoesRouteImport } from './routes/avaliacoes'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperLoginRouteImport } from './routes/super/login'
import { Route as ServicoNovoRouteImport } from './routes/servico.novo'
import { Route as ServicoIdRouteImport } from './routes/servico.$id'
import { Route as AvaliarTokenRouteImport } from './routes/avaliar.$token'
import { Route as AgendarSlugRouteImport } from './routes/agendar.$slug'
import { Route as SuperAppRouteRouteImport } from './routes/super/_app/route'
import { Route as SuperAppIndexRouteImport } from './routes/super/_app/index'
import { Route as SuperAppUsuariosRouteImport } from './routes/super/_app/usuarios'
import { Route as SuperAppPlanosRouteImport } from './routes/super/_app/planos'
import { Route as ApiPublicMpWebhookRouteImport } from './routes/api/public/mp-webhook'
import { Route as ApiPublicMercadoPagoCallbackRouteImport } from './routes/api/public/mercado-pago.callback'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const TransacoesRoute = TransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const SaudacaoRoute = SaudacaoRouteImport.update({
  id: '/saudacao',
  path: '/saudacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoRoute = PlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizacaoRoute = PersonalizacaoRouteImport.update({
  id: '/personalizacao',
  path: '/personalizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilPublicoRoute = PerfilPublicoRouteImport.update({
  id: '/perfil-publico',
  path: '/perfil-publico',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilProfissionalRoute = PerfilProfissionalRouteImport.update({
  id: '/perfil-profissional',
  path: '/perfil-profissional',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentosRoute = PagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesTodasRoute = NotificacoesTodasRouteImport.update({
  id: '/notificacoes-todas',
  path: '/notificacoes-todas',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisRoute = MaisRouteImport.update({
  id: '/mais',
  path: '/mais',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HorariosRoute = HorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleCalendarRoute = GoogleCalendarRouteImport.update({
  id: '/google-calendar',
  path: '/google-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ExemploPaginaRoute = ExemploPaginaRouteImport.update({
  id: '/exemplo-pagina',
  path: '/exemplo-pagina',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacoesRoute = AvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperLoginRoute = SuperLoginRouteImport.update({
  id: '/super/login',
  path: '/super/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicoNovoRoute = ServicoNovoRouteImport.update({
  id: '/servico/novo',
  path: '/servico/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicoIdRoute = ServicoIdRouteImport.update({
  id: '/servico/$id',
  path: '/servico/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliarTokenRoute = AvaliarTokenRouteImport.update({
  id: '/avaliar/$token',
  path: '/avaliar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarSlugRoute = AgendarSlugRouteImport.update({
  id: '/agendar/$slug',
  path: '/agendar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAppRouteRoute = SuperAppRouteRouteImport.update({
  id: '/super/_app',
  path: '/super',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAppIndexRoute = SuperAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAppRouteRoute,
} as any)
const SuperAppUsuariosRoute = SuperAppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => SuperAppRouteRoute,
} as any)
const SuperAppPlanosRoute = SuperAppPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => SuperAppRouteRoute,
} as any)
const ApiPublicMpWebhookRoute = ApiPublicMpWebhookRouteImport.update({
  id: '/api/public/mp-webhook',
  path: '/api/public/mp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMercadoPagoCallbackRoute =
  ApiPublicMercadoPagoCallbackRouteImport.update({
    id: '/api/public/mercado-pago/callback',
    path: '/api/public/mercado-pago/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/cadastro': typeof CadastroRoute
  '/clientes': typeof ClientesRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRoute
  '/exemplo-pagina': typeof ExemploPaginaRoute
  '/google-calendar': typeof GoogleCalendarRoute
  '/horarios': typeof HorariosRoute
  '/login': typeof LoginRoute
  '/mais': typeof MaisRoute
  '/notificacoes': typeof NotificacoesRoute
  '/notificacoes-todas': typeof NotificacoesTodasRoute
  '/onboarding': typeof OnboardingRoute
  '/pagamentos': typeof PagamentosRoute
  '/perfil-profissional': typeof PerfilProfissionalRoute
  '/perfil-publico': typeof PerfilPublicoRoute
  '/personalizacao': typeof PersonalizacaoRoute
  '/plano': typeof PlanoRoute
  '/portfolio': typeof PortfolioRoute
  '/precos': typeof PrecosRoute
  '/recursos': typeof RecursosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saudacao': typeof SaudacaoRoute
  '/servicos': typeof ServicosRoute
  '/transacoes': typeof TransacoesRoute
  '/whatsapp': typeof WhatsappRoute
  '/super': typeof SuperAppRouteRouteWithChildren
  '/agendar/$slug': typeof AgendarSlugRoute
  '/avaliar/$token': typeof AvaliarTokenRoute
  '/servico/$id': typeof ServicoIdRoute
  '/servico/novo': typeof ServicoNovoRoute
  '/super/login': typeof SuperLoginRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/super/planos': typeof SuperAppPlanosRoute
  '/super/usuarios': typeof SuperAppUsuariosRoute
  '/super/': typeof SuperAppIndexRoute
  '/api/public/mercado-pago/callback': typeof ApiPublicMercadoPagoCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/cadastro': typeof CadastroRoute
  '/clientes': typeof ClientesRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRoute
  '/exemplo-pagina': typeof ExemploPaginaRoute
  '/google-calendar': typeof GoogleCalendarRoute
  '/horarios': typeof HorariosRoute
  '/login': typeof LoginRoute
  '/mais': typeof MaisRoute
  '/notificacoes': typeof NotificacoesRoute
  '/notificacoes-todas': typeof NotificacoesTodasRoute
  '/onboarding': typeof OnboardingRoute
  '/pagamentos': typeof PagamentosRoute
  '/perfil-profissional': typeof PerfilProfissionalRoute
  '/perfil-publico': typeof PerfilPublicoRoute
  '/personalizacao': typeof PersonalizacaoRoute
  '/plano': typeof PlanoRoute
  '/portfolio': typeof PortfolioRoute
  '/precos': typeof PrecosRoute
  '/recursos': typeof RecursosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saudacao': typeof SaudacaoRoute
  '/servicos': typeof ServicosRoute
  '/transacoes': typeof TransacoesRoute
  '/whatsapp': typeof WhatsappRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/avaliar/$token': typeof AvaliarTokenRoute
  '/servico/$id': typeof ServicoIdRoute
  '/servico/novo': typeof ServicoNovoRoute
  '/super/login': typeof SuperLoginRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/super/planos': typeof SuperAppPlanosRoute
  '/super/usuarios': typeof SuperAppUsuariosRoute
  '/super': typeof SuperAppIndexRoute
  '/api/public/mercado-pago/callback': typeof ApiPublicMercadoPagoCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/cadastro': typeof CadastroRoute
  '/clientes': typeof ClientesRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRoute
  '/exemplo-pagina': typeof ExemploPaginaRoute
  '/google-calendar': typeof GoogleCalendarRoute
  '/horarios': typeof HorariosRoute
  '/login': typeof LoginRoute
  '/mais': typeof MaisRoute
  '/notificacoes': typeof NotificacoesRoute
  '/notificacoes-todas': typeof NotificacoesTodasRoute
  '/onboarding': typeof OnboardingRoute
  '/pagamentos': typeof PagamentosRoute
  '/perfil-profissional': typeof PerfilProfissionalRoute
  '/perfil-publico': typeof PerfilPublicoRoute
  '/personalizacao': typeof PersonalizacaoRoute
  '/plano': typeof PlanoRoute
  '/portfolio': typeof PortfolioRoute
  '/precos': typeof PrecosRoute
  '/recursos': typeof RecursosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saudacao': typeof SaudacaoRoute
  '/servicos': typeof ServicosRoute
  '/transacoes': typeof TransacoesRoute
  '/whatsapp': typeof WhatsappRoute
  '/super/_app': typeof SuperAppRouteRouteWithChildren
  '/agendar/$slug': typeof AgendarSlugRoute
  '/avaliar/$token': typeof AvaliarTokenRoute
  '/servico/$id': typeof ServicoIdRoute
  '/servico/novo': typeof ServicoNovoRoute
  '/super/login': typeof SuperLoginRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/super/_app/planos': typeof SuperAppPlanosRoute
  '/super/_app/usuarios': typeof SuperAppUsuariosRoute
  '/super/_app/': typeof SuperAppIndexRoute
  '/api/public/mercado-pago/callback': typeof ApiPublicMercadoPagoCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/avaliacoes'
    | '/cadastro'
    | '/clientes'
    | '/contato'
    | '/dashboard'
    | '/exemplo-pagina'
    | '/google-calendar'
    | '/horarios'
    | '/login'
    | '/mais'
    | '/notificacoes'
    | '/notificacoes-todas'
    | '/onboarding'
    | '/pagamentos'
    | '/perfil-profissional'
    | '/perfil-publico'
    | '/personalizacao'
    | '/plano'
    | '/portfolio'
    | '/precos'
    | '/recursos'
    | '/reset-password'
    | '/saudacao'
    | '/servicos'
    | '/transacoes'
    | '/whatsapp'
    | '/super'
    | '/agendar/$slug'
    | '/avaliar/$token'
    | '/servico/$id'
    | '/servico/novo'
    | '/super/login'
    | '/api/public/mp-webhook'
    | '/super/planos'
    | '/super/usuarios'
    | '/super/'
    | '/api/public/mercado-pago/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/avaliacoes'
    | '/cadastro'
    | '/clientes'
    | '/contato'
    | '/dashboard'
    | '/exemplo-pagina'
    | '/google-calendar'
    | '/horarios'
    | '/login'
    | '/mais'
    | '/notificacoes'
    | '/notificacoes-todas'
    | '/onboarding'
    | '/pagamentos'
    | '/perfil-profissional'
    | '/perfil-publico'
    | '/personalizacao'
    | '/plano'
    | '/portfolio'
    | '/precos'
    | '/recursos'
    | '/reset-password'
    | '/saudacao'
    | '/servicos'
    | '/transacoes'
    | '/whatsapp'
    | '/agendar/$slug'
    | '/avaliar/$token'
    | '/servico/$id'
    | '/servico/novo'
    | '/super/login'
    | '/api/public/mp-webhook'
    | '/super/planos'
    | '/super/usuarios'
    | '/super'
    | '/api/public/mercado-pago/callback'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/avaliacoes'
    | '/cadastro'
    | '/clientes'
    | '/contato'
    | '/dashboard'
    | '/exemplo-pagina'
    | '/google-calendar'
    | '/horarios'
    | '/login'
    | '/mais'
    | '/notificacoes'
    | '/notificacoes-todas'
    | '/onboarding'
    | '/pagamentos'
    | '/perfil-profissional'
    | '/perfil-publico'
    | '/personalizacao'
    | '/plano'
    | '/portfolio'
    | '/precos'
    | '/recursos'
    | '/reset-password'
    | '/saudacao'
    | '/servicos'
    | '/transacoes'
    | '/whatsapp'
    | '/super/_app'
    | '/agendar/$slug'
    | '/avaliar/$token'
    | '/servico/$id'
    | '/servico/novo'
    | '/super/login'
    | '/api/public/mp-webhook'
    | '/super/_app/planos'
    | '/super/_app/usuarios'
    | '/super/_app/'
    | '/api/public/mercado-pago/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  AvaliacoesRoute: typeof AvaliacoesRoute
  CadastroRoute: typeof CadastroRoute
  ClientesRoute: typeof ClientesRoute
  ContatoRoute: typeof ContatoRoute
  DashboardRoute: typeof DashboardRoute
  ExemploPaginaRoute: typeof ExemploPaginaRoute
  GoogleCalendarRoute: typeof GoogleCalendarRoute
  HorariosRoute: typeof HorariosRoute
  LoginRoute: typeof LoginRoute
  MaisRoute: typeof MaisRoute
  NotificacoesRoute: typeof NotificacoesRoute
  NotificacoesTodasRoute: typeof NotificacoesTodasRoute
  OnboardingRoute: typeof OnboardingRoute
  PagamentosRoute: typeof PagamentosRoute
  PerfilProfissionalRoute: typeof PerfilProfissionalRoute
  PerfilPublicoRoute: typeof PerfilPublicoRoute
  PersonalizacaoRoute: typeof PersonalizacaoRoute
  PlanoRoute: typeof PlanoRoute
  PortfolioRoute: typeof PortfolioRoute
  PrecosRoute: typeof PrecosRoute
  RecursosRoute: typeof RecursosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SaudacaoRoute: typeof SaudacaoRoute
  ServicosRoute: typeof ServicosRoute
  TransacoesRoute: typeof TransacoesRoute
  WhatsappRoute: typeof WhatsappRoute
  SuperAppRouteRoute: typeof SuperAppRouteRouteWithChildren
  AgendarSlugRoute: typeof AgendarSlugRoute
  AvaliarTokenRoute: typeof AvaliarTokenRoute
  ServicoIdRoute: typeof ServicoIdRoute
  ServicoNovoRoute: typeof ServicoNovoRoute
  SuperLoginRoute: typeof SuperLoginRoute
  ApiPublicMpWebhookRoute: typeof ApiPublicMpWebhookRoute
  ApiPublicMercadoPagoCallbackRoute: typeof ApiPublicMercadoPagoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transacoes': {
      id: '/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof TransacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saudacao': {
      id: '/saudacao'
      path: '/saudacao'
      fullPath: '/saudacao'
      preLoaderRoute: typeof SaudacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano': {
      id: '/plano'
      path: '/plano'
      fullPath: '/plano'
      preLoaderRoute: typeof PlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalizacao': {
      id: '/personalizacao'
      path: '/personalizacao'
      fullPath: '/personalizacao'
      preLoaderRoute: typeof PersonalizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil-publico': {
      id: '/perfil-publico'
      path: '/perfil-publico'
      fullPath: '/perfil-publico'
      preLoaderRoute: typeof PerfilPublicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil-profissional': {
      id: '/perfil-profissional'
      path: '/perfil-profissional'
      fullPath: '/perfil-profissional'
      preLoaderRoute: typeof PerfilProfissionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos': {
      id: '/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof PagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes-todas': {
      id: '/notificacoes-todas'
      path: '/notificacoes-todas'
      fullPath: '/notificacoes-todas'
      preLoaderRoute: typeof NotificacoesTodasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mais': {
      id: '/mais'
      path: '/mais'
      fullPath: '/mais'
      preLoaderRoute: typeof MaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horarios': {
      id: '/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof HorariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-calendar': {
      id: '/google-calendar'
      path: '/google-calendar'
      fullPath: '/google-calendar'
      preLoaderRoute: typeof GoogleCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exemplo-pagina': {
      id: '/exemplo-pagina'
      path: '/exemplo-pagina'
      fullPath: '/exemplo-pagina'
      preLoaderRoute: typeof ExemploPaginaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacoes': {
      id: '/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof AvaliacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/login': {
      id: '/super/login'
      path: '/super/login'
      fullPath: '/super/login'
      preLoaderRoute: typeof SuperLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servico/novo': {
      id: '/servico/novo'
      path: '/servico/novo'
      fullPath: '/servico/novo'
      preLoaderRoute: typeof ServicoNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servico/$id': {
      id: '/servico/$id'
      path: '/servico/$id'
      fullPath: '/servico/$id'
      preLoaderRoute: typeof ServicoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliar/$token': {
      id: '/avaliar/$token'
      path: '/avaliar/$token'
      fullPath: '/avaliar/$token'
      preLoaderRoute: typeof AvaliarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/$slug': {
      id: '/agendar/$slug'
      path: '/agendar/$slug'
      fullPath: '/agendar/$slug'
      preLoaderRoute: typeof AgendarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/_app': {
      id: '/super/_app'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof SuperAppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/_app/': {
      id: '/super/_app/'
      path: '/'
      fullPath: '/super/'
      preLoaderRoute: typeof SuperAppIndexRouteImport
      parentRoute: typeof SuperAppRouteRoute
    }
    '/super/_app/usuarios': {
      id: '/super/_app/usuarios'
      path: '/usuarios'
      fullPath: '/super/usuarios'
      preLoaderRoute: typeof SuperAppUsuariosRouteImport
      parentRoute: typeof SuperAppRouteRoute
    }
    '/super/_app/planos': {
      id: '/super/_app/planos'
      path: '/planos'
      fullPath: '/super/planos'
      preLoaderRoute: typeof SuperAppPlanosRouteImport
      parentRoute: typeof SuperAppRouteRoute
    }
    '/api/public/mp-webhook': {
      id: '/api/public/mp-webhook'
      path: '/api/public/mp-webhook'
      fullPath: '/api/public/mp-webhook'
      preLoaderRoute: typeof ApiPublicMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercado-pago/callback': {
      id: '/api/public/mercado-pago/callback'
      path: '/api/public/mercado-pago/callback'
      fullPath: '/api/public/mercado-pago/callback'
      preLoaderRoute: typeof ApiPublicMercadoPagoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SuperAppRouteRouteChildren {
  SuperAppPlanosRoute: typeof SuperAppPlanosRoute
  SuperAppUsuariosRoute: typeof SuperAppUsuariosRoute
  SuperAppIndexRoute: typeof SuperAppIndexRoute
}

const SuperAppRouteRouteChildren: SuperAppRouteRouteChildren = {
  SuperAppPlanosRoute: SuperAppPlanosRoute,
  SuperAppUsuariosRoute: SuperAppUsuariosRoute,
  SuperAppIndexRoute: SuperAppIndexRoute,
}

const SuperAppRouteRouteWithChildren = SuperAppRouteRoute._addFileChildren(
  SuperAppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  AvaliacoesRoute: AvaliacoesRoute,
  CadastroRoute: CadastroRoute,
  ClientesRoute: ClientesRoute,
  ContatoRoute: ContatoRoute,
  DashboardRoute: DashboardRoute,
  ExemploPaginaRoute: ExemploPaginaRoute,
  GoogleCalendarRoute: GoogleCalendarRoute,
  HorariosRoute: HorariosRoute,
  LoginRoute: LoginRoute,
  MaisRoute: MaisRoute,
  NotificacoesRoute: NotificacoesRoute,
  NotificacoesTodasRoute: NotificacoesTodasRoute,
  OnboardingRoute: OnboardingRoute,
  PagamentosRoute: PagamentosRoute,
  PerfilProfissionalRoute: PerfilProfissionalRoute,
  PerfilPublicoRoute: PerfilPublicoRoute,
  PersonalizacaoRoute: PersonalizacaoRoute,
  PlanoRoute: PlanoRoute,
  PortfolioRoute: PortfolioRoute,
  PrecosRoute: PrecosRoute,
  RecursosRoute: RecursosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SaudacaoRoute: SaudacaoRoute,
  ServicosRoute: ServicosRoute,
  TransacoesRoute: TransacoesRoute,
  WhatsappRoute: WhatsappRoute,
  SuperAppRouteRoute: SuperAppRouteRouteWithChildren,
  AgendarSlugRoute: AgendarSlugRoute,
  AvaliarTokenRoute: AvaliarTokenRoute,
  ServicoIdRoute: ServicoIdRoute,
  ServicoNovoRoute: ServicoNovoRoute,
  SuperLoginRoute: SuperLoginRoute,
  ApiPublicMpWebhookRoute: ApiPublicMpWebhookRoute,
  ApiPublicMercadoPagoCallbackRoute: ApiPublicMercadoPagoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
