// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function getSupabaseEnv() {
  const url = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const key  = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!url || !key) {
    const missing = [
      ...(!url  ? ['SUPABASE_URL'] : []),
      ...(!key  ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return { url, key };
}

function createSupabaseClient() {
  const { url, key } = getSupabaseEnv();

  if (typeof window === 'undefined') {
    // SSR — sem persistência de sessão; o servidor usa Bearer tokens via auth-attacher
    return createClient<Database>(url, key, {
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });
  }

  // Browser — sessão em localStorage. Auth e app vivem no mesmo origin
  // (app.suaagenda.pro), então não há necessidade de cookies cross-subdomínio.
  // localStorage é mais confiável no mobile (sem limites/chunking de cookie).
  return createClient<Database>(url, key, {
    auth: {
      storage:            window.localStorage,
      persistSession:     true,
      autoRefreshToken:   true,
      detectSessionInUrl: true,
    },
  });
}

let _supabase: ReturnType<typeof createClient<Database>> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createClient<Database>>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient() as ReturnType<typeof createClient<Database>>;
    return Reflect.get(_supabase, prop, receiver);
  },
});
